# Generated by Django 4.0.10 on 2023-03-26 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="teams",
            name="update_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
