# Generated by Django 4.0.10 on 2023-03-15 05:30

import django.utils.timezone
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbase",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="userbase",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="userbase",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="userbase",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. \
                    A user will get all permissions granted \
                    to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="userbase",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log \
                    into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="userbase",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user \
                    has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="userbase",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user \
                    should be treated as active. Unselect \
                    this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
