# Generated by Django 4.0.10 on 2023-03-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "accounts",
            "0004_alter_userbase_groups_alter_userbase_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbase",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. \
                    A user will get all permissions \
                    granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be\
                    treated as active. Unselect this \
                    instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can \
                    log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user \
                    has all permissions without \
                    explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
