# Generated by Django 4.0.10 on 2023-03-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_userbase_groups_alter_userbase_is_active_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        height_field=100,
                        upload_to="media/user/profie/",
                        width_field=100,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        height_field=100,
                        upload_to="media/user/cover/",
                        width_field=100,
                    ),
                ),
                ("address", models.TextField(default="")),
                (
                    "secondary_education",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "higher_education",
                    models.CharField(blank=True, max_length=150),
                ),
                ("graduation", models.BooleanField(default=False)),
                ("aboutus", models.TextField(default="")),
                (
                    "specilization",
                    models.CharField(default="", max_length=150),
                ),
                ("github", models.URLField()),
                ("linkedIn", models.URLField()),
                ("facebook", models.URLField()),
                ("instagram", models.URLField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profile",
                    ),
                ),
            ],
        ),
    ]
