# Generated by Django 4.0.10 on 2023-03-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_image",
            field=models.FileField(blank=True, upload_to="media/user/cover/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedIn",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.FileField(blank=True, upload_to="media/user/profie/"),
        ),
    ]
